// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Olydispay_api_backend.Models;

#nullable disable

namespace Olydispay_api_backend.Migrations
{
    [DbContext(typeof(OlydispayApiContext))]
    partial class OlydispayApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Olydispay_api_backend.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentID");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Olydispay_api_backend.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("contractEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("contractStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<int>("gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("jobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("listOfPersonManaged")
                        .HasColumnType("TEXT");

                    b.Property<int?>("managerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("Olydispay_api_backend.Models.GradeHistory", b =>
                {
                    b.Property<int>("GradeHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("fromDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("grade")
                        .HasColumnType("TEXT");

                    b.Property<string>("toDate")
                        .HasColumnType("TEXT");

                    b.HasKey("GradeHistoryID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("gradeHistories");
                });

            modelBuilder.Entity("Olydispay_api_backend.Models.Employee", b =>
                {
                    b.HasOne("Olydispay_api_backend.Models.Department", "department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.Navigation("department");
                });

            modelBuilder.Entity("Olydispay_api_backend.Models.GradeHistory", b =>
                {
                    b.HasOne("Olydispay_api_backend.Models.Employee", "employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID");

                    b.Navigation("employee");
                });
#pragma warning restore 612, 618
        }
    }
}
